Repository uriyyo/fastapi-pagination, pull requests merged in 2024-12, with the labels that each got.

#1384 Fix issue with sqlalchemy select with session.query
  fastapi_pagination/ext/sqlalchemy.py
Labels: bug

#1390 Add ci-prepare script to setup db
  .github/workflows/test.yml
  scripts/ci-prepare.sh
  scripts/ci-test.sh
Labels: enhancement

#1395 Remove unnecessary line from techniques doc
  docs/learn/pagination/techniques.md
Labels: documentation

#1396 Improve spelling in add_to_route.md
  docs/learn/tutorial_user_guide/add_to_route.md
Labels: documentation

#1403 Add ability to quote/unquote cursor
  docs/customization/customizers/use_quoted_cursor.md
  fastapi_pagination/cursor.py
  fastapi_pagination/customization.py
  tests/ext/test_sqlalchemy_cursor.py
  tests/test_cursor.py
  tests/test_customization.py
Labels: enhancement

#1415 Remove deprecated API
  fastapi_pagination/api.py
  fastapi_pagination/async_paginator.py
  fastapi_pagination/bases.py
  fastapi_pagination/default.py
  fastapi_pagination/ext/async_sqlalchemy.py
  fastapi_pagination/ext/async_sqlmodel.py
  fastapi_pagination/ext/sqlalchemy.py
  fastapi_pagination/ext/sqlalchemy_future.py
  fastapi_pagination/limit_offset.py
  scripts/ci-prepare.sh
  tests/ext/test_async_sqlalchemy.py
  tests/ext/test_async_sqlmodel.py
  tests/ext/test_sqlalchemy_future.py
  tests/test_bases.py
  tests/test_paginator.py
Labels: enhancement

#1416 Test suites refactoring
  fastapi_pagination/ext/motor.py
  poetry.lock
  scripts/ci-test.sh
  tests/base.py
  tests/base/__init__.py
  tests/base/builder.py
  tests/base/decorators.py
  tests/base/reflect.py
  tests/base/suite.py
  tests/base/types.py
  tests/conftest.py
  tests/ext/conftest.py
  tests/ext/test_async_sqlalchemy.py
  tests/ext/test_async_sqlmodel.py
  tests/ext/test_asyncpg.py
  tests/ext/test_beanie.py
  tests/ext/test_bunnet.py
  tests/ext/test_cassandra.py
  tests/ext/test_databases.py
  tests/ext/test_django.py
  tests/ext/test_gino.py
  tests/ext/test_mongoengine.py
  tests/ext/test_motor.py
  tests/ext/test_motor_aggregate.py
  tests/ext/test_odmantic.py
  tests/ext/test_orm.py
  tests/ext/test_ormar.py
  tests/ext/test_piccolo.py
  tests/ext/test_pony.py
  tests/ext/test_pymongo.py
  tests/ext/test_sqlalchemy.py
  tests/ext/test_sqlalchemy_cursor.py
  tests/ext/test_sqlalchemy_deprecated.py
  tests/ext/test_sqlalchemy_from_statement.py
  tests/ext/test_sqlalchemy_future.py
  tests/ext/test_sqlalchemy_text.py
  tests/ext/test_sqlmodel.py
  tests/ext/test_tortoise.py
  tests/ext/utils.py
  tests/test_async_paginator.py
  tests/test_iterables.py
  tests/test_paginator.py
  tests/utils.py
Labels: enhancement

#1417 Update tests cov
  fastapi_pagination/ext/sqlalchemy.py
  fastapi_pagination/ext/sqlmodel.py
  fastapi_pagination/ext/utils.py
  fastapi_pagination/links/default.py
  fastapi_pagination/links/limit_offset.py
  tests/ext/test_utils.py
  tests/test_api.py
  tests/test_customization.py
  tests/test_utils.py
Labels: enhancement

#1418 Refactor sqlalchemy tests and tests setup
  tests/base/__init__.py
  tests/base/decorators.py
  tests/conftest.py
  tests/ext/conftest.py
  tests/ext/test_async_sqlalchemy.py
  tests/ext/test_async_sqlmodel.py
  tests/ext/test_cassandra.py
  tests/ext/test_sqlalchemy.py
  tests/ext/test_sqlalchemy_cursor.py
  tests/ext/test_sqlalchemy_deprecated.py
  tests/ext/test_sqlalchemy_from_statement.py
  tests/ext/test_sqlalchemy_future.py
  tests/ext/test_sqlalchemy_text.py
  tests/ext/test_sqlmodel.py
  tests/utils.py
Labels: enhancement
