Repository uriyyo/fastapi-pagination, pull requests merged in 2024-10, with the labels that each got.

#1313 Fix issue with SQLAlchemy scalar select detection
  fastapi_pagination/ext/sqlalchemy.py
  tests/ext/test_sqlalchemy.py
Labels: bug

#1316 Add unwrap mode for `sqlalchemy` ext
  fastapi_pagination/ext/sqlalchemy.py
  fastapi_pagination/ext/utils.py
  tests/ext/test_sqlalchemy.py
Labels: enhancement

#1317 Fix issue when select model with single field
  fastapi_pagination/ext/sqlalchemy.py
Labels: bug

#1325 Add NotImplementedError to ignored exc
  fastapi_pagination/ext/sqlalchemy.py
  pyproject.toml
Labels: bug

#1348 Fix a typo in the elements docs
  docs/learn/tutorial_user_guide/elements.md
Labels: documentation
