Repository uriyyo/fastapi-pagination, pull requests merged in 2024-09, with the labels that each got.

#1277 Add support for sqlalchemy from statement
  examples/pagination_sqlalchemy.py
  fastapi_pagination/ext/sqlalchemy.py
  tests/ext/test_sqlalchemy_from_statement.py
Labels: enhancement

#1269 ✨ Support `total` parameter for tortoise ext
  fastapi_pagination/ext/tortoise.py
Labels: enhancement

#1281 Add better logic for scalars unwrapping
  examples/pagination_sqlalchemy.py
  fastapi_pagination/ext/sqlalchemy.py
Labels: bug, enhancement

#1282 Fix issue with sqlalchemy imports for Gino ext
  fastapi_pagination/ext/sqlalchemy.py
Labels: bug

#1283 Add tests for sqlachemy scalar unwrap logic
  tests/ext/test_sqlalchemy.py
Labels: enhancement
